from waggle_wan_tunnel import scan_sshuttle_pids, scan_sshuttle_chains_and_rules
import unittest

example_ps = """grep  12345
sshuttle   3412
awk  9999
sshuttle   7777
awk  30000
awk  30001
awk  30002
"""

example_iptables_save = """# Generated by iptables-save v1.6.1 on Wed Jan 12 15:44:12 2022
*nat
:PREROUTING ACCEPT [31:2998]
:INPUT ACCEPT [15:1768]
:OUTPUT ACCEPT [19:2542]
:POSTROUTING ACCEPT [47:4558]
:DOCKER - [0:0]
:KUBE-KUBELET-CANARY - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-PROXY-CANARY - [0:0]
:KUBE-SEP-3H6QDI3FCQYJO6PT - [0:0]
:KUBE-SEP-4LFACCGIICXUXE7B - [0:0]
:KUBE-SEP-DNK5QGLSB3KVH7BQ - [0:0]
:KUBE-SEP-FKBAFHEMNDLWAALR - [0:0]
:KUBE-SEP-HJ6JUUSGKFLH6SYV - [0:0]
:KUBE-SEP-JI5KKLFVQ7B7PWNZ - [0:0]
:KUBE-SEP-JPBQ3X6W7QH5H7LS - [0:0]
:KUBE-SEP-KIIPWNCXDWEKYBT2 - [0:0]
:KUBE-SEP-TQXN53BVG3SCL3PK - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-2STFWSCOU27WSA32 - [0:0]
:KUBE-SVC-BSAKFRI6I3YYFBBB - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-JD5MR3NA4I4DYORP - [0:0]
:KUBE-SVC-LSIKXCMNVDDKYYMT - [0:0]
:KUBE-SVC-MNKDTBK4XPDRQ5OJ - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-QMWWTXBG7KFJQKLO - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:sshuttle-12300 - [0:0]
:sshuttle-12301 - [0:0]
-A PREROUTING -j sshuttle-12300
-A PREROUTING -j sshuttle-12301
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -j sshuttle-12300
-A OUTPUT -j sshuttle-12301
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -o wan0 -j MASQUERADE
-A POSTROUTING -o wifi0 -j MASQUERADE
-A POSTROUTING -o modem0 -j MASQUERADE
-A POSTROUTING -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
-A POSTROUTING -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.42.0.0/16 -d 10.42.0.0/24 -j RETURN
-A POSTROUTING ! -s 10.42.0.0/16 -d 10.42.0.0/16 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE
-A KUBE-SEP-3H6QDI3FCQYJO6PT -s 10.42.0.9/32 -m comment --comment "default/wes-rabbitmq:amqp" -j KUBE-MARK-MASQ
-A KUBE-SEP-3H6QDI3FCQYJO6PT -p tcp -m comment --comment "default/wes-rabbitmq:amqp" -m tcp -j DNAT --to-destination 10.42.0.9:5672
-A KUBE-SEP-4LFACCGIICXUXE7B -s 10.42.0.9/32 -m comment --comment "default/wes-rabbitmq:rabbitmq-management" -j KUBE-MARK-MASQ
-A KUBE-SEP-4LFACCGIICXUXE7B -p tcp -m comment --comment "default/wes-rabbitmq:rabbitmq-management" -m tcp -j DNAT --to-destination 10.42.0.9:15672
-A KUBE-SEP-DNK5QGLSB3KVH7BQ -s 10.42.0.11/32 -m comment --comment "kube-system/kube-dns:metrics" -j KUBE-MARK-MASQ
-A KUBE-SEP-DNK5QGLSB3KVH7BQ -p tcp -m comment --comment "kube-system/kube-dns:metrics" -m tcp -j DNAT --to-destination 10.42.0.11:9153
-A KUBE-SEP-FKBAFHEMNDLWAALR -s 10.42.0.11/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-FKBAFHEMNDLWAALR -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.42.0.11:53
-A KUBE-SEP-HJ6JUUSGKFLH6SYV -s 10.42.0.6/32 -m comment --comment "kube-system/metrics-server" -j KUBE-MARK-MASQ
-A KUBE-SEP-HJ6JUUSGKFLH6SYV -p tcp -m comment --comment "kube-system/metrics-server" -m tcp -j DNAT --to-destination 10.42.0.6:443
-A KUBE-SEP-JI5KKLFVQ7B7PWNZ -s 10.42.0.83/32 -m comment --comment "default/node-influxdb:node-influxdb" -j KUBE-MARK-MASQ
-A KUBE-SEP-JI5KKLFVQ7B7PWNZ -p tcp -m comment --comment "default/node-influxdb:node-influxdb" -m tcp -j DNAT --to-destination 10.42.0.83:8086
-A KUBE-SEP-JPBQ3X6W7QH5H7LS -s 10.31.81.1/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-JPBQ3X6W7QH5H7LS -p tcp -m comment --comment "default/kubernetes:https" -m tcp -j DNAT --to-destination 10.31.81.1:6443
-A KUBE-SEP-KIIPWNCXDWEKYBT2 -s 10.42.0.11/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-KIIPWNCXDWEKYBT2 -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.42.0.11:53
-A KUBE-SEP-TQXN53BVG3SCL3PK -s 10.42.0.2/32 -m comment --comment "default/wes-gps-server:gpsd" -j KUBE-MARK-MASQ
-A KUBE-SEP-TQXN53BVG3SCL3PK -p tcp -m comment --comment "default/wes-gps-server:gpsd" -m tcp -j DNAT --to-destination 10.42.0.2:2947
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.192.158/32 -p tcp -m comment --comment "default/wes-rabbitmq:amqp cluster IP" -m tcp --dport 5672 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.192.158/32 -p tcp -m comment --comment "default/wes-rabbitmq:amqp cluster IP" -m tcp --dport 5672 -j KUBE-SVC-MNKDTBK4XPDRQ5OJ
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.192.158/32 -p tcp -m comment --comment "default/wes-rabbitmq:rabbitmq-management cluster IP" -m tcp --dport 15672 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.192.158/32 -p tcp -m comment --comment "default/wes-rabbitmq:rabbitmq-management cluster IP" -m tcp --dport 15672 -j KUBE-SVC-2STFWSCOU27WSA32
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:metrics cluster IP" -m tcp --dport 9153 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:metrics cluster IP" -m tcp --dport 9153 -j KUBE-SVC-JD5MR3NA4I4DYORP
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.19.129/32 -p tcp -m comment --comment "kube-system/metrics-server cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.19.129/32 -p tcp -m comment --comment "kube-system/metrics-server cluster IP" -m tcp --dport 443 -j KUBE-SVC-QMWWTXBG7KFJQKLO
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.22.65/32 -p tcp -m comment --comment "default/wes-gps-server:gpsd cluster IP" -m tcp --dport 2947 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.22.65/32 -p tcp -m comment --comment "default/wes-gps-server:gpsd cluster IP" -m tcp --dport 2947 -j KUBE-SVC-BSAKFRI6I3YYFBBB
-A KUBE-SERVICES ! -s 10.42.0.0/16 -d 10.43.103.33/32 -p tcp -m comment --comment "default/node-influxdb:node-influxdb cluster IP" -m tcp --dport 8086 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.43.103.33/32 -p tcp -m comment --comment "default/node-influxdb:node-influxdb cluster IP" -m tcp --dport 8086 -j KUBE-SVC-LSIKXCMNVDDKYYMT
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-2STFWSCOU27WSA32 -m comment --comment "default/wes-rabbitmq:rabbitmq-management" -j KUBE-SEP-4LFACCGIICXUXE7B
-A KUBE-SVC-BSAKFRI6I3YYFBBB -m comment --comment "default/wes-gps-server:gpsd" -j KUBE-SEP-TQXN53BVG3SCL3PK
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-FKBAFHEMNDLWAALR
-A KUBE-SVC-JD5MR3NA4I4DYORP -m comment --comment "kube-system/kube-dns:metrics" -j KUBE-SEP-DNK5QGLSB3KVH7BQ
-A KUBE-SVC-LSIKXCMNVDDKYYMT -m comment --comment "default/node-influxdb:node-influxdb" -j KUBE-SEP-JI5KKLFVQ7B7PWNZ
-A KUBE-SVC-MNKDTBK4XPDRQ5OJ -m comment --comment "default/wes-rabbitmq:amqp" -j KUBE-SEP-3H6QDI3FCQYJO6PT
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-JPBQ3X6W7QH5H7LS
-A KUBE-SVC-QMWWTXBG7KFJQKLO -m comment --comment "kube-system/metrics-server" -j KUBE-SEP-HJ6JUUSGKFLH6SYV
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-KIIPWNCXDWEKYBT2
-A sshuttle-12300 -d 10.31.81.0/24 -p tcp -j RETURN
-A sshuttle-12300 -d 192.5.0.0/16 -p tcp -j RETURN
-A sshuttle-12300 -d 10.42.0.0/16 -p tcp -j RETURN
-A sshuttle-12300 -d 10.43.0.0/16 -p tcp -j RETURN
-A sshuttle-12300 -p tcp -m ttl ! --ttl-eq 42 -j REDIRECT --to-ports 12300
-A sshuttle-12301 -d 10.31.81.0/24 -p tcp -j RETURN
-A sshuttle-12301 -d 192.5.0.0/16 -p tcp -j RETURN
-A sshuttle-12301 -d 10.42.0.0/16 -p tcp -j RETURN
-A sshuttle-12301 -d 10.43.0.0/16 -p tcp -j RETURN
-A sshuttle-12301 -p tcp -m ttl ! --ttl-eq 42 -j REDIRECT --to-ports 12301
COMMIT
# Completed on Wed Jan 12 15:44:12 2022
"""

class TestProgram(unittest.TestCase):

    def test_scan_sshuttle_pids(self):
        pids = scan_sshuttle_pids(example_ps)
        self.assertCountEqual(pids, ["3412", "7777"])
    
    def test_scan_sshuttle_chains_and_rules(self):
        chains, rules = scan_sshuttle_chains_and_rules(example_iptables_save)

        self.assertCountEqual(chains, [
            "sshuttle-12300",
            "sshuttle-12301",
        ])

        self.assertCountEqual(rules, [
            "PREROUTING -j sshuttle-12300",
            "OUTPUT -j sshuttle-12300",
            "sshuttle-12300 -d 10.31.81.0/24 -p tcp -j RETURN",
            "sshuttle-12300 -d 192.5.0.0/16 -p tcp -j RETURN",
            "sshuttle-12300 -d 10.42.0.0/16 -p tcp -j RETURN",
            "sshuttle-12300 -d 10.43.0.0/16 -p tcp -j RETURN",
            "sshuttle-12300 -p tcp -m ttl ! --ttl-eq 42 -j REDIRECT --to-ports 12300",
            "PREROUTING -j sshuttle-12301",
            "OUTPUT -j sshuttle-12301",
            "sshuttle-12301 -d 10.31.81.0/24 -p tcp -j RETURN",
            "sshuttle-12301 -d 192.5.0.0/16 -p tcp -j RETURN",
            "sshuttle-12301 -d 10.42.0.0/16 -p tcp -j RETURN",
            "sshuttle-12301 -d 10.43.0.0/16 -p tcp -j RETURN",
            "sshuttle-12301 -p tcp -m ttl ! --ttl-eq 42 -j REDIRECT --to-ports 12301",
        ])


if __name__ == "__main__":
    unittest.main()
